workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "TechMaths4"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace App/App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/build/App.xcarchive
    artifacts:
      - build/**/*.ipa
      - ios/App/build/Release-iphoneos/*.app
    publishing:
      email:
        recipients:
          - "jkan79creations@gmail.com"
