workflows:
  ios_unsigned:
    name: iOS Unsigned Build
    environment:
      vars:
        APP_NAME: "TechMaths4"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Fix permissions and sync Capacitor iOS
        script: |
          chmod +x node_modules/.bin/cap
          npx cap sync ios
      - name: Build iOS app (unsigned)
        script: |
          cd ios/App
          xcodebuild -scheme App -configuration Release -sdk iphoneos -archivePath ../build/App.xcarchive archive
    artifacts:
      - ios/build/**/*.xcarchive
      - ios/App/build/Release-iphoneos/*.app
